title: Multilogin Coupon & Guides
email: ''
description: 'Multilogin coupons, tutorials and automation guides.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anti-detect.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
default_lang: en
languages:
  - en
  - pt
  - ru
  - vi
  - zh
lang_names:
  en: "English"
  pt: "Português"
  ru: "Русский"
  vi: "Tiếng Việt"
  zh: "中文 (中国)"
